[program:voracbt-queue-default]
command=php /var/www/voracbt/current/bin/queue-work-redis --queue=default --sleep=1 --tries=3 --memory=512
directory=/var/www/voracbt/current
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=4
process_name=%(program_name)s_%(process_num)02d
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/voracbt/shared/storage/logs/queue.log

[program:voracbt-queue-exam]
command=php /var/www/voracbt/current/bin/queue-work-redis --queue=exam-critical --sleep=1 --tries=5 --memory=512
directory=/var/www/voracbt/current
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=2
process_name=%(program_name)s_%(process_num)02d
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/voracbt/shared/storage/logs/queue.log
